### ISSUE TITLE
能否给出For标签具体示例

### ISSUE THREAD

**Issue by fanslead** [dotnetcore/SmartCode#10]
我看官方文档只有部分标签有具体示例，在使用其他标签时不太清楚用法。
能否补全一下文档或在此issue下回复一下具体示例。谢谢
![image](https://user-images.githubusercontent.com/22066473/47275262-5e858780-d5e0-11e8-9c82-ef954c192809.png)

**Comment by Ahoo-Wang** [comment]
重复 #11
