### ISSUE TITLE
能否给出标签具体示例

### ISSUE THREAD

**Issue by fanslead** [dotnetcore/SmartCode#11]
官方文档只有部分标签具体示例，能否补全一下文档标签具体使用示例。
例如For标签，想使用插入操作却不知道具体如何使用。
或者在这ISSUE下提供一下For标签的具体示例，谢谢。
![image](https://user-images.githubusercontent.com/22066473/47275512-a1e0f580-d5e2-11e8-9692-9edb9927866e.png)

**Comment by Ahoo-Wang** [comment]
@fanslead 这个你应该在 https://github.com/Ahoo-Wang/SmartSql 提问噢。

![image](https://user-images.githubusercontent.com/4384159/47294427-a091e600-d63f-11e8-87da-28ace6c3e093.png)
![image](https://user-images.githubusercontent.com/4384159/47294434-a687c700-d63f-11e8-82d4-eecf8750bee8.png)
![image](https://user-images.githubusercontent.com/4384159/47294452-b0112f00-d63f-11e8-8726-fdae4f8422e4.png)
![image](https://user-images.githubusercontent.com/4384159/47294464-b4d5e300-d63f-11e8-93f0-0b90b3c5a652.png)

**Comment by Ahoo-Wang** [comment]
@fanslead 今天 github 出问题了，刚刚看到你的 issue

**Comment by fanslead** [comment]
@Ahoo-Wang 好的，昨天github出问题了，所以提了两次，以为第一次没成功~~
