### ISSUE TITLE
mysql xml中方法GetEntity问题

### ISSUE THREAD

**Issue by ByronFeng** [dotnetcore/SmartCode#21]
![qqg 8u 6vo 6khsha54mp](https://user-images.githubusercontent.com/26641643/50501731-5a209380-0a95-11e9-9e6f-91a145b4b4f0.png)

TEntity GetById([Param("Id")] TPrimary id);
        TEntity GetEntity(object reqParams);

这个方法GetEntity就没有实际意义，需要修改成全条件查询

**Comment by Ahoo-Wang** [comment]
可以自定义模板
