### ISSUE TITLE
NamingConverter: Camel 全部变小写了

### ISSUE THREAD

**Issue by icewindq** [dotnetcore/SmartCode#22]
首先谢谢 @Ahoo-Wang 写的这个非常好用的工具，有个小问题，当我设置NamingConverter: Camel时，所有词都变成小写了，
问题应该出在这一行
https://github.com/Smart-Kit/SmartCode/blob/93ecc932900220f2b7d4f723cad39e42c6ba5589/src/SmartCode/WordsConverter/CamelCaseConverter.cs#L20

**Comment by Ahoo-Wang** [comment]
感谢你提交的PR，已合并。
