### ISSUE TITLE
DB字段命名里有下划线时，生成的Map文件所对应的属性移除了下划线

### ISSUE THREAD

**Issue by harvey0720** [dotnetcore/SmartCode#29]
表结构：
CREATE TABLE Sys_Area(
	F_Id varchar(50) NOT NULL comment '标识列',
	F_ParentId varchar(50) NULL comment '父级',
	F_Layers int NULL  comment '层次',
	F_EnCode varchar(50) NULL  comment '编码',
	F_FullName varchar(50) NULL  comment '名称',
	F_SimpleSpelling varchar(50) NULL  comment '简拼',
	F_SortCode int NULL  comment '排序码',
	F_DeleteMark bit NULL  comment '删除标志',
	F_EnabledMark bit NULL  comment '有效标志',
	F_Description varchar(500) NULL  comment '描述',
	F_CreatorTime datetime NULL comment '创建日期',
	F_CreatorUserId varchar(50) NULL comment '创建用户主键',
	F_LastModifyTime datetime NULL comment '最后修改时间',
	F_LastModifyUserId varchar(50) NULL comment '最后修改用户',
	F_DeleteTime datetime NULL comment '删除时间',
	F_DeleteUserId varchar(50) NULL comment '删除用户',
	F_CreatorUserName varchar(50) NOT NULL DEFAULT '超级管理员',
	F_DeleteUserName varchar(50) NULL,
	F_LastModifyUserName varchar(50) NULL,
	primary key (F_Id)
) ;
使用smartcode.yml默认设置，生成的Map里GetEntity把

![QQ五笔截图未命名](https://user-images.githubusercontent.com/44251369/58240501-b3a79880-7d7d-11e9-84c8-2ae950d33426.png)。在获取数据时给出提示：Statement:SysArea.GetEntity Tag:Where Min-matched:1 but matched:0 fail.

**Comment by Ahoo-Wang** [comment]
贴模板

**Comment by Ahoo-Wang** [comment]
你这个情况的建议是 配置转换的时候设置移除 前缀 F_ ，F_Id -> Id，这个比较符合规范。
