### ISSUE TITLE
能否将 IncludeTables IgnoreTables IgnoreNoPKTable IgnoreView 这些属性也移动到全局配置？

### ISSUE THREAD

**Issue by beginor** [dotnetcore/SmartCode#32]
如题， 请问能否考虑将 `IncludeTables` `IgnoreTables` `IgnoreNoPKTable` `IgnoreView` 这些属性添加到全局配置。

多数情况下每个 Build 下的 Task 的配置是相同的， 现在是每个 Task 都要写这些配置， 修改起来比较麻烦。

Task 默认读取全局的这些配置， 如果 Task 下重新定义了这些属性， 则`IncludeTables` `IgnoreTables`可以和全局定义的进行合并，`IgnoreNoPKTable` `IgnoreView`  则以 Task 的配置为准。

**Comment by Ahoo-Wang** [comment]
ok，下个小版本迭代一下这个功能，目前命名转换部分支持全局默认配置了。

**Comment by beginor** [comment]
期待更新！

**Comment by Ahoo-Wang** [comment]
已更新。
