### ISSUE TITLE
提交建议：希望像mybatis提供编写外部插件的功能

### ISSUE THREAD

**Issue by zhanjian** [dotnetcore/SmartCode#45]
提交建议：希望像mybatis提供编写外部插件的功能，另外一个感谢昨天提供类图以供研究

**Comment by ElderJames** [comment]
smartcode本身支持扩展，而跟mybatis对标的是smartsql，请问你有提交错地方吗？

**Comment by Ahoo-Wang** [comment]
你或许应该到 https://github.com/dotnetcore/SmartSql/issues 提交你的建议。
