### ISSUE TITLE
哪有教程教怎么写模板,好让我们贡献出来

### ISSUE THREAD

**Issue by gxlqssjf** [dotnetcore/SmartCode#49]
哪有教程教怎么写模板,好让我们贡献出来

**Comment by Ahoo-Wang** [comment]
Please refer to the code in the source code.
--> https://github.com/dotnetcore/SmartCode/blob/master/src/SmartCode.Generator/RazorTemplates/

---
Here are the relevant contribution specifications:
https://github.com/dotnetcore/SmartCode/issues/9
