### ISSUE TITLE
PgSql生成模板字段需要加上双引号

### ISSUE THREAD

**Issue by fanslead** [dotnetcore/SmartCode#5]
由于PgSql的识别规则，sql语句中表字段需要用双引号包起来，否则执行语句是会异常。
最后生成应该要这样才行。
![image](https://user-images.githubusercontent.com/22066473/47192634-e4a39300-d380-11e8-89af-ca6ab1345212.png)

**Comment by Ahoo-Wang** [comment]
@fanslead OK，感谢提醒！


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by beginor** [comment]
pg 数据库建议使用蛇形 (snake_case) 命名规范， 不要区分大小写

**Comment by fanslead** [comment]
> pg 数据库建议使用蛇形 (snake_case) 命名规范， 不要区分大小写

昨天已经试过这种命名规范，执行sql依旧出现异常，只有用双引号包起来才能执行

**Comment by beginor** [comment]
@fanslead 可能是列中有关键字吧，要不就是 smart sql 的问题了

**Comment by Ahoo-Wang** [comment]
@fanslead @beginor SmartSql也只是转发SQL，我猜可能是pg命名的问题。
@fanslead 方便的话给我你的SQL脚本，以便于我今晚复现该问题，并给出修复方案。

**Comment by beginor** [comment]
@Ahoo-Wang 数据库有问题？ 更多的可能应该是 sql 的问题吧

**Comment by Ahoo-Wang** [comment]
@beginor 命名有可能有问题，就是你刚刚说的啊。


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by fanslead** [comment]
@Ahoo-Wang 这是sql脚本，我判断应该是pgsql的命名识别规则的原因。
[sql.txt](https://github.com/Ahoo-Wang/SmartCode/files/2494570/sql.txt)

**Comment by Ahoo-Wang** [comment]
@fanslead ok，感谢，晚上我来check一下。

**Comment by Ahoo-Wang** [comment]
@fanslead @beginor 

![image](https://user-images.githubusercontent.com/4384159/47238125-b58a3180-d413-11e8-997c-fd925ee1e7ca.png)
![image](https://user-images.githubusercontent.com/4384159/47238006-4b718c80-d413-11e8-87a4-ee67ee49f765.png)

![image](https://user-images.githubusercontent.com/4384159/47238738-b45a0400-d415-11e8-8a88-9b3fb1e6029d.png)

可以看出SQL语句执行是会全部转成小写的，跟ORM是没有关系的。

下面这条是可以执行成功的，因为都是小写。 建议字段名不要使用大写以免造成不必要的麻烦。
![image](https://user-images.githubusercontent.com/4384159/47238645-72c95900-d415-11e8-92a7-20fa216cd265.png)

**Comment by fanslead** [comment]
@Ahoo-Wang OK,我把表字段改成纯小写命名吧
