### ISSUE TITLE
Use .NET 5 as framework

### ISSUE THREAD

**Issue by moalamri** [dotnetcore/SmartCode#60]
Hi, 
Whenever I run the generator command I get the following error:
```
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '2.2.0' was not found.
  - The following frameworks were found:
      2.1.24 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      3.1.11 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      5.0.2 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

I understand that it only support .NET 2.2.0, but wanted to ask if there's a way to change the target framework in the configuration file? Or it's 2.2.0 the only default option? I scrolled around the issues to figure if someone has asked this, but I couldn't understand..

Thank you...

**Comment by beginor** [comment]
please look at issue #48
