### ISSUE TITLE
支持一对多，多对多的生成吗？

### ISSUE THREAD

**Issue by a-tony** [dotnetcore/SmartCode#61]
支持一对多，多对多的生成吗？支持自定义sql语句吗？我想利用你这个开发一个低代码工具

**Comment by Ahoo-Wang** [comment]
建议问题描述再详细一点。要不然很难理解你所说的 一对多，多对多是指什么意思、自定义SQL语句又是指什么？问题/需求场景尽量描述清楚一些。

**Comment by a-tony** [comment]
好比现在有一个表单，表单要输入一些数据，举个例子：1、用户表user
2、用户技能表user_skill
3、一个用户有多个技能
4、从页面中新增一个用户，同时会选择多个用户技能，此时向后端controller发送请求，
后端的action如何接收到前端的请求，并且能够插入user和user_skill
这是一种一对多的关系，一对多搞定了，多对多其实也一样的道理，我看了很多低代码平台，耦合性太重了，要耦合很多东西，我不想耦合那么多东西，所以我想借助您这个轮子，完善一下代码生成器

**Comment by Ahoo-Wang** [comment]
支持的。

**Comment by a-tony** [comment]
好的，我今天试试看，如果可以，我到时候在你的基础上再完善，然后再贡献给你
