### ISSUE TITLE
更新mysql.data

### ISSUE THREAD

**Issue by d0apga** [dotnetcore/SmartCode#67]
MySql.Data 8.0.19 无法识别information_schema utf8mb3字符集， 需要更新到最新版本8.0.29

**Comment by Ahoo-Wang** [comment]
> MySql.Data 8.0.19 无法识别information_schema utf8mb3字符集， 需要更新到最新版本8.0.29

Can you help us submit this PR?

**Comment by d0apga** [comment]
> > MySql.Data 8.0.19 无法识别information_schema utf8mb3字符集， 需要更新到最新版本8.0.29
> 
> Can you help us submit this PR?

合并到net6分支还是master分支？

**Comment by Ahoo-Wang** [comment]
> > > MySql.Data 8.0.19 无法识别information_schema utf8mb3字符集， 需要更新到最新版本8.0.29
> > 
> > 
> > Can you help us submit this PR?
> 
> 合并到net6分支还是master分支？

master

**Comment by d0apga** [comment]
#68
