### ISSUE TITLE
支持数据表的外键关系么？

### ISSUE THREAD

**Issue by beginor** [dotnetcore/SmartCode#8]
看了 `SmartCode.Db.Entity. Column` 的定义， 貌似不支持数据表的外键关系，是这样么？

**Comment by Ahoo-Wang** [comment]
是的，目前还不支持。

**Comment by beginor** [comment]
请问有支持外键的计划么？

**Comment by Ahoo-Wang** [comment]
@beginor 最近比较忙，这个特性可能要稍微晚点。
你可以提交PR的，修改方式也比较简单。
1. 增加外键关系结构相关SQL，SQL都在目录https://github.com/Ahoo-Wang/SmartCode/tree/master/src/SmartCode.Db/Maps 里边
2. 增加 SmartCode.Db.Entity. Column 外键关系属性

**Comment by Ahoo-Wang** [comment]
@beginor 昨天GitHub抽风了，昨天就看到你的回复了，但是点开是空的。

**Comment by beginor** [comment]
好的， 有时间尝试一下
